POST http://localhost:4002/products
content-type: application/json

{
  "name": "magan fox",
  "price": 10
}

###

GET http://localhost:4002/products

###
GET http://localhost:4002/products/a3e90325-779d-484d-8d01-6d390690f686